# Generated by Django 4.1.7 on 2023-04-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField(max_length=18)),
            ],
        ),
    ]
